import { Title } from '@mantine/core';
import Head from 'next/head';

import { DefaultLayout } from '@/components';

export default function HomePage() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Title sx={(theme) => ({ color: theme.colors.brand[6] })}>kkakaka</Title>
    </>
  );
}

HomePage.getLayout = function getLayout(page: React.ReactElement) {
  return <DefaultLayout>{page}</DefaultLayout>;
};
